<a href="https://colab.research.google.com/github/abhishekgkofficial-collab/Day-9-Processed-Ecommerce-Dataset/blob/main/Day_9_Processed_Ecommerce_Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# ============================================================
# DAY 9 INTERNSHIP ASSIGNMENT
# PROCESSED E-COMMERCE DATASET
# Python + Pandas
# ============================================================

import pandas as pd
import numpy as np
from google.colab import files

print("=" * 70)
print("DAY 9 - PROCESSED E-COMMERCE DATASET")
print("=" * 70)

# ============================================================
# 1. UPLOAD THREE CSV FILES
# ============================================================

print("\nPlease upload these 3 files:")
print("1. Orders CSV")
print("2. Customers CSV")
print("3. Products CSV")

uploaded = files.upload()

print("\nFiles uploaded successfully!")

# Identify files automatically
orders_file = None
customers_file = None
products_file = None

for file_name in uploaded.keys():

    if "order" in file_name.lower():
        orders_file = file_name

    elif "customer" in file_name.lower():
        customers_file = file_name

    elif "product" in file_name.lower():
        products_file = file_name

print("\nDetected Files:")
print("Orders   :", orders_file)
print("Customers:", customers_file)
print("Products :", products_file)


# ============================================================
# 2. LOAD DATASETS
# ============================================================

orders = pd.read_csv(orders_file)
customers = pd.read_csv(customers_file)
products = pd.read_csv(products_file)

print("\n" + "=" * 70)
print("2. DATASETS LOADED")
print("=" * 70)

print("\nOrders Shape:", orders.shape)
print("Customers Shape:", customers.shape)
print("Products Shape:", products.shape)


# ============================================================
# 3. DISPLAY DATASETS
# ============================================================

print("\n" + "=" * 70)
print("3. DATASET PREVIEW")
print("=" * 70)

print("\nORDERS:")
display(orders.head())

print("\nCUSTOMERS:")
display(customers.head())

print("\nPRODUCTS:")
display(products.head())


# ============================================================
# 4. CHECK DATA TYPES
# ============================================================

print("\n" + "=" * 70)
print("4. DATA TYPES")
print("=" * 70)

print("\nOrders:")
print(orders.dtypes)

print("\nCustomers:")
print(customers.dtypes)

print("\nProducts:")
print(products.dtypes)


# ============================================================
# 5. CHECK MISSING VALUES
# ============================================================

print("\n" + "=" * 70)
print("5. MISSING VALUES")
print("=" * 70)

print("\nOrders Missing Values:")
print(orders.isnull().sum())

print("\nCustomers Missing Values:")
print(customers.isnull().sum())

print("\nProducts Missing Values:")
print(products.isnull().sum())


# ============================================================
# 6. MERGE ORDERS WITH CUSTOMERS
# ============================================================

print("\n" + "=" * 70)
print("6. MERGING ORDERS AND CUSTOMERS")
print("=" * 70)

orders_customers = pd.merge(
    orders,
    customers,
    on="Customer_ID",
    how="left"
)

print("Orders + Customers Shape:",
      orders_customers.shape)

display(orders_customers.head())


# ============================================================
# 7. MERGE WITH PRODUCTS
# ============================================================

print("\n" + "=" * 70)
print("7. MERGING WITH PRODUCTS")
print("=" * 70)

processed_df = pd.merge(
    orders_customers,
    products,
    on="Product_ID",
    how="left"
)

print("Final Merged Shape:",
      processed_df.shape)

display(processed_df.head())


# ============================================================
# 8. CONCAT DEMONSTRATION
# ============================================================

print("\n" + "=" * 70)
print("8. CONCAT DEMONSTRATION")
print("=" * 70)

# Split Orders into two parts
orders_part1 = orders.iloc[:60]
orders_part2 = orders.iloc[60:]

# Combine them using concat()
orders_combined = pd.concat(
    [orders_part1, orders_part2],
    ignore_index=True
)

print("First Part Shape:", orders_part1.shape)
print("Second Part Shape:", orders_part2.shape)
print("Combined Shape:", orders_combined.shape)

print("\nCombined DataFrame:")
display(orders_combined.head())


# ============================================================
# 9. DATETIME CONVERSION
# ============================================================

print("\n" + "=" * 70)
print("9. DATETIME PROCESSING")
print("=" * 70)

processed_df["Order_Date"] = pd.to_datetime(
    processed_df["Order_Date"]
)

print("Order_Date converted to:")
print(processed_df["Order_Date"].dtype)


# ============================================================
# 10. EXTRACT DATE INFORMATION
# ============================================================

print("\n" + "=" * 70)
print("10. EXTRACTING DATE INFORMATION")
print("=" * 70)

processed_df["Order_Year"] = (
    processed_df["Order_Date"].dt.year
)

processed_df["Order_Month"] = (
    processed_df["Order_Date"].dt.month
)

processed_df["Order_Month_Name"] = (
    processed_df["Order_Date"].dt.month_name()
)

processed_df["Order_Day"] = (
    processed_df["Order_Date"].dt.day
)

processed_df["Order_Day_Name"] = (
    processed_df["Order_Date"].dt.day_name()
)

display(
    processed_df[
        [
            "Order_Date",
            "Order_Year",
            "Order_Month",
            "Order_Month_Name",
            "Order_Day",
            "Order_Day_Name"
        ]
    ].head(10)
)


# ============================================================
# 11. APPLY() - CREATE TOTAL SALES
# ============================================================

print("\n" + "=" * 70)
print("11. APPLY() - CALCULATING TOTAL SALES")
print("=" * 70)

processed_df["Total_Sales"] = processed_df.apply(
    lambda row: row["Quantity"] * row["Unit_Price"],
    axis=1
)

display(
    processed_df[
        [
            "Order_ID",
            "Product_Name",
            "Quantity",
            "Unit_Price",
            "Total_Sales"
        ]
    ].head(10)
)


# ============================================================
# 12. APPLY() - CREATE ORDER VALUE CATEGORY
# ============================================================

print("\n" + "=" * 70)
print("12. APPLY() - ORDER VALUE CATEGORY")
print("=" * 70)

def classify_order(value):

    if value >= 3000:
        return "High Value"

    elif value >= 1500:
        return "Medium Value"

    else:
        return "Low Value"


processed_df["Order_Value_Category"] = (
    processed_df["Total_Sales"].apply(classify_order)
)

display(
    processed_df[
        [
            "Order_ID",
            "Total_Sales",
            "Order_Value_Category"
        ]
    ].head(10)
)


# ============================================================
# 13. CLEAN FINAL DATAFRAME
# ============================================================

print("\n" + "=" * 70)
print("13. CLEAN PROCESSED DATASET")
print("=" * 70)

final_columns = [
    "Order_ID",
    "Order_Date",
    "Order_Year",
    "Order_Month",
    "Order_Month_Name",
    "Order_Day",
    "Order_Day_Name",
    "Customer_ID",
    "Customer_Name",
    "City",
    "Region",
    "Membership_Type",
    "Product_ID",
    "Product_Name",
    "Category",
    "Brand",
    "Unit_Price",
    "Quantity",
    "Total_Sales",
    "Order_Value_Category",
    "Payment_Method",
    "Order_Status"
]

final_df = processed_df[final_columns].copy()

print("Final Dataset Shape:")
print(final_df.shape)

display(final_df.head(10))


# ============================================================
# 14. BASIC ANALYSIS OF PROCESSED DATA
# ============================================================

print("\n" + "=" * 70)
print("14. PROCESSED DATASET ANALYSIS")
print("=" * 70)

print("\nTotal Orders:",
      final_df["Order_ID"].nunique())

print("Total Quantity Sold:",
      final_df["Quantity"].sum())

print("Total Sales:",
      final_df["Total_Sales"].sum())

print("Average Order Value:",
      final_df["Total_Sales"].mean())

print("Highest Order Value:",
      final_df["Total_Sales"].max())

print("Lowest Order Value:",
      final_df["Total_Sales"].min())


# ============================================================
# 15. SALES BY CATEGORY
# ============================================================

print("\n" + "=" * 70)
print("15. SALES BY CATEGORY")
print("=" * 70)

category_sales = (
    final_df
    .groupby("Category")["Total_Sales"]
    .sum()
    .sort_values(ascending=False)
)

display(category_sales)


# ============================================================
# 16. SALES BY CITY
# ============================================================

print("\n" + "=" * 70)
print("16. SALES BY CITY")
print("=" * 70)

city_sales = (
    final_df
    .groupby("City")["Total_Sales"]
    .sum()
    .sort_values(ascending=False)
)

display(city_sales)


# ============================================================
# 17. SALES BY PRODUCT
# ============================================================

print("\n" + "=" * 70)
print("17. SALES BY PRODUCT")
print("=" * 70)

product_sales = (
    final_df
    .groupby("Product_Name")["Total_Sales"]
    .sum()
    .sort_values(ascending=False)
)

display(product_sales.head(10))


# ============================================================
# 18. SALES BY PAYMENT METHOD
# ============================================================

print("\n" + "=" * 70)
print("18. SALES BY PAYMENT METHOD")
print("=" * 70)

payment_sales = (
    final_df
    .groupby("Payment_Method")["Total_Sales"]
    .sum()
    .sort_values(ascending=False)
)

display(payment_sales)


# ============================================================
# 19. SALES BY MONTH
# ============================================================

print("\n" + "=" * 70)
print("19. MONTHLY SALES")
print("=" * 70)

monthly_sales = (
    final_df
    .groupby("Order_Month_Name")["Total_Sales"]
    .sum()
)

display(monthly_sales)


# ============================================================
# 20. EXPORT FINAL DATASET
# ============================================================

print("\n" + "=" * 70)
print("20. EXPORTING FINAL DATASET")
print("=" * 70)

output_file = "Day9_Processed_Ecommerce_Dataset.csv"

final_df.to_csv(
    output_file,
    index=False
)

print("Processed dataset saved as:")
print(output_file)


# ============================================================
# 21. DOWNLOAD PROCESSED DATASET
# ============================================================

files.download(output_file)


# ============================================================
# 22. FINAL OBSERVATIONS
# ============================================================

print("\n" + "=" * 70)
print("22. FINAL OBSERVATIONS")
print("=" * 70)

best_category = (
    final_df.groupby("Category")["Total_Sales"]
    .sum()
    .idxmax()
)

best_city = (
    final_df.groupby("City")["Total_Sales"]
    .sum()
    .idxmax()
)

best_product = (
    final_df.groupby("Product_Name")["Total_Sales"]
    .sum()
    .idxmax()
)

best_payment = (
    final_df.groupby("Payment_Method")["Total_Sales"]
    .sum()
    .idxmax()
)

print("Best Performing Category:", best_category)
print("Best Performing City:", best_city)
print("Best Performing Product:", best_product)
print("Highest Sales Payment Method:", best_payment)

print("\nTotal Sales:",
      final_df["Total_Sales"].sum())

print("Total Quantity Sold:",
      final_df["Quantity"].sum())

print("Number of Orders:",
      final_df["Order_ID"].nunique())


# ============================================================
# COMPLETED
# ============================================================

print("\n" + "=" * 70)
print("DAY 9 ASSIGNMENT COMPLETED SUCCESSFULLY")
print("=" * 70)

======================================================================
DAY 9 - PROCESSED E-COMMERCE DATASET
======================================================================

Please upload these 3 files:
1. Orders CSV
2. Customers CSV
3. Products CSV

Saving Day9_Orders.csv to Day9_Orders.csv
Saving Day9_Products.csv to Day9_Products.csv
Saving Day9_Customers.csv to Day9_Customers.csv

Files uploaded successfully!

Detected Files:
Orders   : Day9_Orders.csv
Customers: Day9_Customers.csv
Products : Day9_Products.csv

======================================================================
2. DATASETS LOADED
======================================================================

Orders Shape: (120, 7)
Customers Shape: (30, 5)
Products Shape: (20, 5)

======================================================================
3. DATASET PREVIEW
======================================================================

ORDERS:

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Payment_Method,Order_Status
0,O0001,2026-02-19,C027,P019,2,Credit Card,Delivered
1,O0002,2026-01-25,C006,P003,2,Debit Card,Delivered
2,O0003,2026-02-26,C015,P004,1,Cash on Delivery,Delivered
3,O0004,2026-03-04,C024,P015,3,Net Banking,Delivered
4,O0005,2026-03-29,C025,P009,5,Credit Card,Delivered

CUSTOMERS:

  Customer_ID Customer_Name      City Region Membership_Type
0        C001  Aarav Sharma  Srinagar  North         Premium
1        C002     Zoya Khan     Delhi  North         Regular
2        C003   Rohan Mehta    Mumbai   West         Premium
3        C004  Ananya Singh     Jammu  North         Regular
4        C005     Kabir Ali   Lucknow  North             New

PRODUCTS:

  Product_ID         Product_Name     Category  Unit_Price     Brand
0       P001  Wireless Headphones  Electronics        1499  SoundMax
1       P002  Mechanical Keyboard  Electronics        2499    KeyPro
2       P003       Wireless Mouse  Electronics         899  TechGear
3       P004          Smart Watch  Electronics        3299   FitTech
4       P005           Power Bank  Electronics        1199  VoltPlus

======================================================================
4. DATA TYPES
======================================================================

Orders:
Order_ID          object
Order_Date        object
Customer_ID       object
Product_ID        object
Quantity           int64
Payment_Method    object
Order_Status      object
dtype: object

Customers:
Customer_ID        object
Customer_Name      object
City               object
Region             object
Membership_Type    object
dtype: object

Products:
Product_ID      object
Product_Name    object
Category        object
Unit_Price       int64
Brand           object
dtype: object

======================================================================
5. MISSING VALUES
======================================================================

Orders Missing Values:
Order_ID          0
Order_Date        0
Customer_ID       0
Product_ID        0
Quantity          0
Payment_Method    0
Order_Status      0
dtype: int64

Customers Missing Values:
Customer_ID        0
Customer_Name      0
City               0
Region             0
Membership_Type    0
dtype: int64

Products Missing Values:
Product_ID      0
Product_Name    0
Category        0
Unit_Price      0
Brand           0
dtype: int64

======================================================================
6. MERGING ORDERS AND CUSTOMERS
======================================================================
Orders + Customers Shape: (120, 11)

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Payment_Method,Order_Status,Customer_Name,City,Region,Membership_Type
0,O0001,2026-02-19,C027,P019,2,Credit Card,Delivered,Harsh Vardhan,Noida,North,Premium
1,O0002,2026-01-25,C006,P003,2,Debit Card,Delivered,Ishita Gupta,Bengaluru,South,Premium
2,O0003,2026-02-26,C015,P004,1,Cash on Delivery,Delivered,Karan Joshi,Chandigarh,North,Regular
3,O0004,2026-03-04,C024,P015,3,Net Banking,Delivered,Maryam Khan,Hyderabad,South,Regular
4,O0005,2026-03-29,C025,P009,5,Credit Card,Delivered,Reyansh Jain,Kolkata,East,New

======================================================================
7. MERGING WITH PRODUCTS
======================================================================
Final Merged Shape: (120, 15)

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Payment_Method,Order_Status,Customer_Name,City,Region,Membership_Type,Product_Name,Category,Unit_Price,Brand
0,O0001,2026-02-19,C027,P019,2,Credit Card,Delivered,Harsh Vardhan,Noida,North,Premium,Cricket Bat,Sports,2499,BatPro
1,O0002,2026-01-25,C006,P003,2,Debit Card,Delivered,Ishita Gupta,Bengaluru,South,Premium,Wireless Mouse,Electronics,899,TechGear
2,O0003,2026-02-26,C015,P004,1,Cash on Delivery,Delivered,Karan Joshi,Chandigarh,North,Regular,Smart Watch,Electronics,3299,FitTech
3,O0004,2026-03-04,C024,P015,3,Net Banking,Delivered,Maryam Khan,Hyderabad,South,Regular,Machine Learning Basics,Books,999,AIPress
4,O0005,2026-03-29,C025,P009,5,Credit Card,Delivered,Reyansh Jain,Kolkata,East,New,Coffee Maker,Home & Kitchen,3499,HomeBrew

======================================================================
8. CONCAT DEMONSTRATION
======================================================================
First Part Shape: (60, 7)
Second Part Shape: (60, 7)
Combined Shape: (120, 7)

Combined DataFrame:

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Payment_Method,Order_Status
0,O0001,2026-02-19,C027,P019,2,Credit Card,Delivered
1,O0002,2026-01-25,C006,P003,2,Debit Card,Delivered
2,O0003,2026-02-26,C015,P004,1,Cash on Delivery,Delivered
3,O0004,2026-03-04,C024,P015,3,Net Banking,Delivered
4,O0005,2026-03-29,C025,P009,5,Credit Card,Delivered

======================================================================
9. DATETIME PROCESSING
======================================================================
Order_Date converted to:
datetime64[ns]

======================================================================
10. EXTRACTING DATE INFORMATION
======================================================================

,Order_Date,Order_Year,Order_Month,Order_Month_Name,Order_Day,Order_Day_Name
0,2026-02-19,2026,2,February,19,Thursday
1,2026-01-25,2026,1,January,25,Sunday
2,2026-02-26,2026,2,February,26,Thursday
3,2026-03-04,2026,3,March,4,Wednesday
4,2026-03-29,2026,3,March,29,Sunday
5,2026-02-09,2026,2,February,9,Monday
6,2026-02-10,2026,2,February,10,Tuesday
7,2026-03-27,2026,3,March,27,Friday
8,2026-03-13,2026,3,March,13,Friday
9,2026-03-05,2026,3,March,5,Thursday

======================================================================
11. APPLY() - CALCULATING TOTAL SALES
======================================================================

  Order_ID             Product_Name  Quantity  Unit_Price  Total_Sales
0    O0001              Cricket Bat         2        2499         4998
1    O0002           Wireless Mouse         2         899         1798
2    O0003              Smart Watch         1        3299         3299
3    O0004  Machine Learning Basics         3         999         2997
4    O0005             Coffee Maker         5        3499        17495
5    O0006                 Football         3         799         2397
6    O0007           Wireless Mouse         3         899         2697
7    O0008               Power Bank         4        1199         4796
8    O0009             Coffee Maker         2        3499         6998
9    O0010               Power Bank         2        1199         2398

======================================================================
12. APPLY() - ORDER VALUE CATEGORY
======================================================================

  Order_ID  Total_Sales Order_Value_Category
0    O0001         4998           High Value
1    O0002         1798         Medium Value
2    O0003         3299           High Value
3    O0004         2997         Medium Value
4    O0005        17495           High Value
5    O0006         2397         Medium Value
6    O0007         2697         Medium Value
7    O0008         4796           High Value
8    O0009         6998           High Value
9    O0010         2398         Medium Value

======================================================================
13. CLEAN PROCESSED DATASET
======================================================================
Final Dataset Shape:
(120, 22)

,Order_ID,Order_Date,Order_Year,Order_Month,Order_Month_Name,Order_Day,Order_Day_Name,Customer_ID,Customer_Name,City,...,Product_ID,Product_Name,Category,Brand,Unit_Price,Quantity,Total_Sales,Order_Value_Category,Payment_Method,Order_Status
0,O0001,2026-02-19,2026,2,February,19,Thursday,C027,Harsh Vardhan,Noida,...,P019,Cricket Bat,Sports,BatPro,2499,2,4998,High Value,Credit Card,Delivered
1,O0002,2026-01-25,2026,1,January,25,Sunday,C006,Ishita Gupta,Bengaluru,...,P003,Wireless Mouse,Electronics,TechGear,899,2,1798,Medium Value,Debit Card,Delivered
2,O0003,2026-02-26,2026,2,February,26,Thursday,C015,Karan Joshi,Chandigarh,...,P004,Smart Watch,Electronics,FitTech,3299,1,3299,High Value,Cash on Delivery,Delivered
3,O0004,2026-03-04,2026,3,March,4,Wednesday,C024,Maryam Khan,Hyderabad,...,P015,Machine Learning Basics,Books,AIPress,999,3,2997,Medium Value,Net Banking,Delivered
4,O0005,2026-03-29,2026,3,March,29,Sunday,C025,Reyansh Jain,Kolkata,...,P009,Coffee Maker,Home & Kitchen,HomeBrew,3499,5,17495,High Value,Credit Card,Delivered
5,O0006,2026-02-09,2026,2,February,9,Monday,C003,Rohan Mehta,Mumbai,...,P018,Football,Sports,SportZone,799,3,2397,Medium Value,UPI,Delivered
6,O0007,2026-02-10,2026,2,February,10,Tuesday,C011,Vivaan Kapoor,Jaipur,...,P003,Wireless Mouse,Electronics,TechGear,899,3,2697,Medium Value,UPI,Delivered
7,O0008,2026-03-27,2026,3,March,27,Friday,C020,Priya Menon,Chennai,...,P005,Power Bank,Electronics,VoltPlus,1199,4,4796,High Value,Debit Card,Delivered
8,O0009,2026-03-13,2026,3,March,13,Friday,C024,Maryam Khan,Hyderabad,...,P009,Coffee Maker,Home & Kitchen,HomeBrew,3499,2,6998,High Value,UPI,Cancelled
9,O0010,2026-03-05,2026,3,March,5,Thursday,C026,Fatima Noor,Srinagar,...,P005,Power Bank,Electronics,VoltPlus,1199,2,2398,Medium Value,Debit Card,Shipped

======================================================================
14. PROCESSED DATASET ANALYSIS
======================================================================

Total Orders: 120
Total Quantity Sold: 343
Total Sales: 741507
Average Order Value: 6179.225
Highest Order Value: 24995
Lowest Order Value: 599

======================================================================
15. SALES BY CATEGORY
======================================================================

Category
Home & Kitchen    243913
Electronics       177821
Clothing          168033
Sports            116736
Books              35004
Name: Total_Sales, dtype: int64

======================================================================
16. SALES BY CITY
======================================================================

City
Srinagar      132235
Mumbai         77566
Chandigarh     73420
Hyderabad      67964
Bengaluru      57176
Delhi          54221
Jammu          52579
Noida          42387
Pune           40581
Kolkata        35084
Jaipur         33085
Lucknow        28790
Ahmedabad      25888
Chennai        15686
Kochi           4845
Name: Total_Sales, dtype: int64

======================================================================
17. SALES BY PRODUCT
======================================================================

Product_Name
Air Fryer              124975
Sneakers               116961
Smart Watch            115465
Coffee Maker            80477
Cricket Bat             52479
Dumbbell Set            47976
Hoodie                  33579
Power Bank              21582
Electric Kettle         20986
Wireless Headphones     19487
Name: Total_Sales, dtype: int64

======================================================================
18. SALES BY PAYMENT METHOD
======================================================================

Payment_Method
Credit Card         251104
Net Banking         153384
Debit Card          136018
Cash on Delivery    120346
UPI                  80655
Name: Total_Sales, dtype: int64

======================================================================
19. MONTHLY SALES
======================================================================

Order_Month_Name
February    277931
January     226582
March       236994
Name: Total_Sales, dtype: int64

======================================================================
20. EXPORTING FINAL DATASET
======================================================================
Processed dataset saved as:
Day9_Processed_Ecommerce_Dataset.csv

======================================================================
22. FINAL OBSERVATIONS
======================================================================
Best Performing Category: Home & Kitchen
Best Performing City: Srinagar
Best Performing Product: Air Fryer
Highest Sales Payment Method: Credit Card

Total Sales: 741507
Total Quantity Sold: 343
Number of Orders: 120

======================================================================
DAY 9 ASSIGNMENT COMPLETED SUCCESSFULLY
======================================================================